### ISSUE TITLE
uni-app打包成的微信小程序包中，插入的位置不对，放在了page标签中

### ISSUE THREAD

**Issue by cjj4649** [smartXJ/vue3-inset-loader#5]
uni-app打包成的微信小程序包中，插入的位置不对，放在了page标签中，因为不了解插件方面的代码，所以想请作者大大看看是不是我使用的问题，具体引用的步骤和你readme文件中一致，仅修改了导入的标签组件名，插入后的组件也存在dom节点和内容，应该不是使用的问题

**Comment by smartXJ** [comment]
page标签？插件里面的代码就是把就你页面的template拿出来再往里面插入你自定义的标签

**Comment by cjj4649** [comment]
对的，正常我在页面引用组件的话
`<page>
   <view>
      < 引用组件 />
   </view>
</page>`
用你提供的插件是这样的
`<page>
      < 引用组件 />
   <view>
   </view>
</page>`

就是想问问这个能不能调到上面那样

**Comment by smartXJ** [comment]
加了rootEle 标签。
rootEle: 'view' 就会加上第一个view中

**Comment by cjj4649** [comment]
感谢作者大大
